export enum FamilyMember {
  AMEL = 'AMEL',
  ANOUK = 'ANOUK',
  BEATRICE = 'BEATRICE',
  CAROLE = 'CAROLE',
  IMAN = 'IMAN',
  ISMAEL = 'ISMAËL',
  SOFIA = 'SOFIA',
  SOULEIMANE = 'SOULEIMANE',
  ZAKARIA = 'ZAKARIA',
}
